### PR TITLE
Update to Charter, 3/15, Added Bylaw

### PR DESCRIPTION
**Pull request by bradley-evans**
Updated charter incorporates changes requested by Student Life.
Bylaw update more clearly deliniates what a "general member" actually is.

### CODE REVIEW

**Review by tacalvin — APPROVED** [review]
Everything looks good

**Review by tacalvin — APPROVED** [review]
Looks good

**Review by tacalvin — COMMENTED** [review]
Charter updates

**Review by jjkjiang — APPROVED** [review]
I also approve

**Pull request merged**
